# This file was adapted from:
#   - pyvisgen (https://github.com/radionets-project/pyvisgen/blob/main/.pre-commit-config.yaml)
#     Originally licensed under MIT License. Copyright (c) 2021 radionets-project.

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        exclude: __init__.py
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black-jupyter
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: [--max-line-length=100, "--extend-ignore=E203,E741,E731"]
        exclude: "version.py|__init__.py"
